server:
  port: 8084


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: P^ssw0rd213
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: USER-SERVICE
  profiles:
    active: prod
  config:
    import: optional:configserver:http://localhost:8086
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-44416090.okta.com/oauth2/default
        client:
          registration:
            my-internal-client:
              provider: okta
              authorization-grant-type: client_credentials
              scope: internal
              client-id: 0oafeznz062nLv0MD5d7
              client-secret: _YCeWxxCU2lFg3Ph4SnnU8iP4O5G80Ld-uHzaqanGVLsy81zq9N-SVpqRne3Gq5L
          provider:
            okta:
              issuer-uri: https://dev-44416090.okta.com/oauth2/default




#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
      web:
        exposure:
          include: health
  endpoint:
    health:
      show-details: always
resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50 #if our failure rate is more than 50%
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s


  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s

okta:
  oauth2:
    issuer: https://dev-44416090.okta.com/oauth2/default
    audience: api://default




